### ISSUE TITLE
Can't load MIcrosoft.extensions.Logging.LoggerFactoryOptions when running publish

### ISSUE THREAD

**Issue by OsirisTerje** [Dreamescaper/GenerateAspNetCoreClient#1]
Hi!  Interesting tool!

Tried it on a  project and got a loading exception.  The project is .net core.

![image](https://user-images.githubusercontent.com/203432/109398635-5d965a80-793e-11eb-93a0-e5f87242e683.png)

Makes any sense ?

**Comment by Dreamescaper** [comment]
Seems like something is wrong with assembly resolve. 
(I had a lot of issues in that area due to the fact that I need to actually run the web project assembly to get Api Explorer info)

**Comment by Dreamescaper** [comment]
You have ASP.Net Core 3.1 project, right?
Seems like I've broken 3.1 compatibility in latest release in some cases.

**Comment by Dreamescaper** [comment]
@OsirisTerje 
I've added (quite an ugly) workaround to support 3.1 projects, so I hope to have it fixed in 0.3 version. 
Would you be able to check it?

**Comment by Dreamescaper** [comment]
I expect this issue to be fixed, so I'm closing it.
Please let me know if it still happens for you.
