### ISSUE TITLE
Use Existing DLL and not Build csproj (for Larger Solutions)?

### ISSUE THREAD

**Issue by Mike-E-angelo** [Dreamescaper/GenerateAspNetCoreClient#26]
Thank you for your efforts with this project 🙏

Everything works well and I was able to generate the code for my application.

The only concern is build time.  I experience this with EFCore migrations/commands, too, and it's rather frustrating.  It takes about 90 seconds (or longer) for a build to occur, mostly because `dotnet build` does not leverage build acceleration.

Ideally, it would be valuable to have a parameter to use the existing .dll (if it can find it of course) and use that instead of rebuilding the project, which takes a lot of time for larger solutions.

Thank you for any consideration.

**Comment by Dreamescaper** [comment]
It should work if you pass existing dll path:
```
dotnet-generate-client MyApiProject.dll -o OutPath
```

**Comment by Mike-E-angelo** [comment]
> It should work if you pass existing dll path

And it does!  AWESOME!  Thank you @Dreamescaper for that pointer and for your efforts. 🙏🙏🙏
