### ISSUE TITLE
Run Tool in a Post Build Command

### ISSUE THREAD

**Issue by CianToole** [Dreamescaper/GenerateAspNetCoreClient#28]
I am looking to run this tool in a post-build command to automate the generation of the interfaces.  

I have had some trouble getting this to work however, as the command builds the app I seem to get stuck in an infinite loop where the app keeps building and calling the command to generate the interfaces.

I was wondering if there was a way to only run the command once by having the command ignore the post-build command or adding a condition to the post build command that would prevent the command from being run multiple times.

Here is the command that I have now.  Any help would be greatly appreciated.

` <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="if $(ConfigurationName) == Debug(&#xD;&#xA;dotnet-generate-client '$(ProjectDir)' -o '$(SolutionDir)My.App.API\ClientInterfaces' -n 'My.App.API'&#xD;&#xA;&#xD;&#xA;)" />
  </Target>`

**Comment by Dreamescaper** [comment]
Similar issue: https://github.com/Dreamescaper/GenerateAspNetCoreClient/issues/26

You can pass built dll to the tool, that would probably work better.

**Comment by CianToole** [comment]
Awesome! That worked.  Thank you for the quick response!
