### ISSUE TITLE
Generator dont check for query names

### ISSUE THREAD

**Issue by valentasm1** [Dreamescaper/GenerateAspNetCoreClient#4]
Lets say we have Action like this
```
GetThing(string language, [FromQuery(Name = "culture")] string? languageCulture)
```
It generates
```
GetThing(string language, string languageCulture = null);
```

which should be
```
GetThing(string language, [AliasAs("culture")]  string languageCulture = null);
```

Or
```
GetThing(string language, string culture= null);
```

**Comment by valentasm1** [comment]
Workaround would be just name languageCulture  > culture

**Comment by Dreamescaper** [comment]
Thanks for reporting!
I've published updated version.

**Comment by valentasm1** [comment]
I wanted to complain why you closed this without fixing, since it looked to fast to fix it in that short time. After double check i realised that you fixed it. Super fast. Thank you .
