### ISSUE TITLE
Partial interface

### ISSUE THREAD

**Issue by vmachacek** [Dreamescaper/GenerateAspNetCoreClient#8]
I realized when I need to "overwrite" generated functionality mostly to provide different return type for convenience, it would be nice to make interface partial where the generated file would stay the same and I can add custom endpoint in other file keeping them separated and compatible with auto re-generation.

**Comment by Dreamescaper** [comment]
Yup, that makes perfect sense!

**Comment by vmachacek** [comment]
I made this adjustment https://github.com/Dreamescaper/GenerateAspNetCoreClient/commit/67803bee504c29bfccc8a481253befd4ce5d1e4e would that work as a PR?

**Comment by Dreamescaper** [comment]
@vmachacek 
Sure!

**Comment by Dreamescaper** [comment]
Thanks for your contribution, I've published updated version to nuget, please check it out.
https://www.nuget.org/packages/GenerateAspNetCoreClient.Refit/

**Comment by vmachacek** [comment]
wicked, thanks!
