### ISSUE TITLE
Generator dont check for query names for array type

### ISSUE THREAD

**Issue by valentasm1** [Dreamescaper/GenerateAspNetCoreClient#9]
I found very similar issue to this one https://github.com/Dreamescaper/GenerateAspNetCoreClient/issues/4
Lets say i have this. (Dont need to be enum, but any array type)
```
GetThing(string language, [FromQuery(Name = "language_types")] SomeEnum[]? languageTypes)
```
It generates
```
GetThing(string language, [Query] SomeEnum[] languageTypes = null);
```
It should be
```
GetThing(string language, [AliasAs("language_types")]  SomeEnum[] languageTypes = null);
```

**Comment by Dreamescaper** [comment]
I've published updated version to nuget, please check it out.
https://www.nuget.org/packages/GenerateAspNetCoreClient.Refit/

**Comment by valentasm1** [comment]
Awesome. It works. Thank you very much
Slava Ukraini !!!
